name: Jemuran_Otomatis
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


#------------------- PACKAGES ---------------------#
dependencies:
  flutter:
    sdk: flutter
  # Utility Packages
  http: ^1.2.2
  intl: ^0.17.0
  logger: ^2.2.0
  url_launcher: ^6.2.6
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.2.0+3
  connectivity_plus: ^6.0.3
  lottie: ^3.1.0 # OR RIVE

  #Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.4

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Spesific
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2

  # Firebase
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2
  firebase_storage: ^11.7.4


  #--------------------- ./ PACKAGES END -------------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  #------------------------ LOCAL ASSETS ----------------------#
  assets:
    - assets/logos/
    
  #------------------------ LOCAL FONTS -----------------------#
  fonts:
    - family: Raleway
      fonts:
        - asset : assets/fonts/Raleway-Black.ttf
          weight : 300
        - asset : assets/fonts/Raleway-Bold.ttf
          weight : 400
        - asset : assets/fonts/Raleway-BoldItalic.ttf
          weight : 400
          style : italic
        - asset : assets/fonts/Raleway-ExtraBold.ttf
          weight : 500
        - asset : assets/fonts/Raleway-ExtraBoldItalic.ttf
          weight : 500
          style : italic
        - asset : assets/fonts/Raleway-ExtraLight.ttf
          weight : 600
        - asset : assets/fonts/Raleway-ExtraLightItalic.ttf
          weight : 600
          style : italic
        - asset : assets/fonts/Raleway-Italic.ttf
          weight : 700
        - asset : assets/fonts/Raleway-Light.ttf
          weight : 800
        - asset : assets/fonts/Raleway-LightItalic.ttf
          weight : 800
          style : italic
        - asset : assets/fonts/Raleway-Medium.ttf
          weight : 500
        - asset : assets/fonts/Raleway-MediumItalic.ttf
          weight : 500
          style : italic
        - asset : assets/fonts/Raleway-Regular.ttf
          weight : 600
        - asset : assets/fonts/Raleway-SemiBold.ttf
          weight : 700
        - asset : assets/fonts/Raleway-SemiBoldItalic.ttf
          weight : 700
          style : italic
        - asset : assets/fonts/Raleway-Thin.ttf
          weight : 800
        - asset : assets/fonts/Raleway-ThinItalic.ttf
          weight : 800
          style : italic